# permissions for end users to view istioconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istioconfiguration-viewer-role
rules:
- apiGroups:
  - kyma.kyma-project.io
  resources:
  - istioconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kyma.kyma-project.io
  resources:
  - istioconfigurations/status
  verbs:
  - get
